# === DOCKER COMPOSE PARA DESENVOLVIMENTO ===
# Sistema de Agendamentos - Ambiente DEV
# Uso: docker-compose -f docker-compose.dev.yml up

services:
  # === NGINX PARA DESENVOLVIMENTO ===
  agendamentos_nginx_dev:
    image: nginx:alpine
    container_name: agendamentos_nginx_dev
    restart: unless-stopped
    ports:
      - "8080:80"  # Aplicação principal
      - "8081:81"  # Nginx status (opcional)
    volumes:
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
      - ./storage:/var/www/html/storage
      - ./resources:/var/www/html/resources  # Para hot reload
    networks:
      - agendamentos_dev_network
    depends_on:
      - agendamentos_app_dev
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template

  # === APLICAÇÃO LARAVEL PARA DESENVOLVIMENTO ===
  agendamentos_app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: agendamentos_app_dev
    restart: unless-stopped
    ports:
      - "9000:9000"  # PHP-FPM
      - "5173:5173"  # Vite dev server
    volumes:
      # Montar todo o código para desenvolvimento ativo
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor  # Cache do vendor
      - ./node_modules:/var/www/html/node_modules  # Cache do node_modules
      # Configurações específicas
      - ./.env.dev:/var/www/html/.env
      # Logs para debug
      - ./storage/logs:/var/www/html/storage/logs
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - PHP_IDE_CONFIG=serverName=agendamentos-dev
      - XDEBUG_MODE=develop,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
    networks:
      - agendamentos_dev_network
    depends_on:
      - redis_agendamentos_dev
    working_dir: /var/www/html
    command: >
      sh -c "composer install --dev &&
             npm install &&
             php artisan key:generate --force &&
             php artisan migrate --force &&
             php artisan db:seed --force &&
             php artisan storage:link &&
             php artisan config:clear &&
             php artisan route:clear &&
             php artisan view:clear &&
             supervisord -c /etc/supervisor/conf.d/supervisord.dev.conf"

  # === REDIS PARA DESENVOLVIMENTO ===
  redis_agendamentos_dev:
    image: redis:7-alpine
    container_name: redis_agendamentos_dev
    restart: unless-stopped
    ports:
      - "6379:6379"  # Expor para acesso direto
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_agendamentos_dev_data:/data
    networks:
      - agendamentos_dev_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # === MAILHOG PARA TESTE DE EMAILS ===
  mailhog_dev:
    image: mailhog/mailhog:latest
    container_name: agendamentos_mailhog_dev
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - agendamentos_dev_network

  # === ADMINER PARA GERENCIAR BANCO ===
  adminer_dev:
    image: adminer:latest
    container_name: agendamentos_adminer_dev
    restart: unless-stopped
    ports:
      - "8082:8080"
    networks:
      - agendamentos_dev_network
    environment:
      - ADMINER_DEFAULT_SERVER=agendamentos_app_dev

# === REDES ===
networks:
  agendamentos_dev_network:
    driver: bridge
    name: agendamentos_dev_network

# === VOLUMES ===
volumes:
  redis_agendamentos_dev_data:
    driver: local
    name: agendamentos_redis_dev_data